// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace JobPocDemo.Data.Migrations
{
    [DbContext(typeof(JobDbContext))]
    class JobDbContextModelSnapshot : ModelSnapshot
    {
        #region methods

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("JobPocDemo.Data.JobItem",
                                b =>
                                {
                                    b.Property<int>("Id")
                                     .ValueGeneratedOnAdd()
                                     .HasColumnType("INTEGER");

                                    b.Property<string>("Content")
                                     .IsRequired()
                                     .HasColumnType("TEXT");

                                    b.Property<string>("Type")
                                     .IsRequired()
                                     .HasColumnType("TEXT");

                                    b.HasKey("Id");

                                    b.ToTable("Jobs");
                                });
#pragma warning restore 612, 618
        }

        #endregion
    }
}
